### ISSUE TITLE
Question about sextractor_path

### ISSUE THREAD

**Issue by druidowm** [astrotuvi/pyplate#7]
Hi,

I am trying to incorporate pyplate into a project my school is working on. However, we have run into an issue. We get the following error:

Traceback (most recent call last):
  File "StarRemoval.py", line 18, in <module>
    psPipe.single_image(args["input"])
  File "/anaconda3/lib/python3.7/site-packages/pyplate/pipeline.py", line 161, in single_image
    proc.extract_sources()
  File "/anaconda3/lib/python3.7/site-packages/pyplate/solve.py", line 1105, in extract_sources
    sex_ver = sp.check_output([self.sextractor_path, '-v']).strip()
  File "/anaconda3/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/anaconda3/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/anaconda3/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sex': 'sex'

We have figured out that we need to set sextractor_path in the config file. However, we do not know what sextractor_path represents or what it is used for. Could you help us figure this out?

Thank you in advance for any assistance!

druidowm

**Comment by astrotuvi** [comment]
Hi,

Thanks for your interest in PyPlate. To extract sources from an image, PyPlate relies on the SExtractor software ([https://www.astromatic.net/software/sextractor](url)) and sextractor_path is used for specifying the location of the SExtractor executable file on disk. The error message says that the executable (by default, named 'sex') was not found.

However, PyPlate is intended for processing scans of photographic plates (negatives) and probably it will not be of much help for your purposes.

Cheers,
Taavi
