### ISSUE TITLE
Installation issue with Python 3 and mysql capability

### ISSUE THREAD

**Issue by lupinix** [astrotuvi/pyplate#8]
When I use pip install pyplate[solve,mysql] to install pyplate on Python 3, I end up with 
`Using cached https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3jn9ma15/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pip-install-3jn9ma15/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'`

This is a result of the fact, that MySQL-python (which you require in setup.py) is not Python 3 compatible. Afaik mysqlclient [1]  can be considered as a drop-in replacement which supports Python 3, but I did not test this yet.

Greetings,
Christian

[1] https://pypi.org/project/mysqlclient/

**Comment by astrotuvi** [comment]
Thanks for raising this issue. Unfortunately I cannot provide a quick fix, because I do not have the dependencies of mysqlclient on my development system. In the coming month or two we will implement Postgres connection, as this is what we need ourselves for the next APPLAUSE data release.

**Comment by lupinix** [comment]
For our local setup I will test with mysqlclient when we come to that point, technically I guess I'm able to fix this. So this is not a blocker for us :) Maybe we're slow enough to start with Postgres direckty then :D
